### ISSUE TITLE
Working perfectly! Until.. 

### ISSUE THREAD

**Issue by lowgoz** [micolous/cbus#10]
Firstly, i love what you've done! 

I've managed to create a docker from the master repo you updated yesterday, changing the last line of the docker file in order to connect to my CNI:
`cmqttd -b 192.168.1.3 -t 192.168.1.8:10001 --broker-disable-tls ` then built using Unraid and executed the image. 

It behaved as expected and created all the discovered MQTT devices in Home Assistant and I was able to control Cbus as designed. Worked perfectly for 4 hours then crashed:

```
Current time: Sun, 23 Feb 2020 08:34:53 +1000
2020-02-23 08:34:54,337 Transport security disabled!
2020-02-23 08:34:54,343 Connected to MQTT broker
2020-02-23 12:59:55,080 Fatal error: protocol.data_received() call failed.
protocol: <cbus.daemon.cmqttd.CBusHandler object at 0x146a523e4c70>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
File "/usr/lib/python3.8/asyncio/selector_events.py", line 860, in _read_ready__data_received
self._protocol.data_received(data)
File "/usr/lib/python3.8/site-packages/cbus/protocol/buffered_protocol.py", line 79, in data_received
raise ValueError(
ValueError: Received data would make the buffer exceed the maximum limit, buffer dropped!
```

Am also getting random errors on starting, but attempting to start again seems to resolve the issue

```
Current time: Sun, 23 Feb 2020 18:38:33 +1000
2020-02-23 18:38:33,963 Transport security disabled!
2020-02-23 18:38:33,974 Connected to MQTT broker
2020-02-23 18:38:34,122 Fatal error: protocol.data_received() call failed.

protocol: <cbus.daemon.cmqttd.CBusHandler object at 0x14b75ae99c70>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
File "/usr/lib/python3.8/asyncio/selector_events.py", line 860, in _read_ready__data_received
self._protocol.data_received(data)
File "/usr/lib/python3.8/site-packages/cbus/protocol/buffered_protocol.py", line 86, in data_received
self._process_buffer()
File "/usr/lib/python3.8/site-packages/cbus/protocol/buffered_protocol.py", line 95, in _process_buffer
r = self.handle_data(bytes(self._buf))
File "/usr/lib/python3.8/site-packages/cbus/protocol/cbus_protocol.py", line 68, in handle_data
p, remainder = decode_packet(
File "/usr/lib/python3.8/site-packages/cbus/protocol/packet.py", line 231, in decode_packet
p = PointToPointPacket.decode_packet(
File "/usr/lib/python3.8/site-packages/cbus/protocol/pp_packet.py", line 146, in decode_packet
cal, cal_len = cls.decode_cal(data)
File "/usr/lib/python3.8/site-packages/cbus/protocol/pp_packet.py", line 113, in decode_cal
handler = REQUESTS[cmd]
KeyError: 50
```

**Comment by lowgoz** [comment]
re-built from your latest update yesterday and has been stable for 8 hours. Fingers crossed !!!
