### ISSUE TITLE
Received data would make the buffer exceed the maximum limit, buffer dropped

### ISSUE THREAD

**Issue by lowgoz** [micolous/cbus#14]
I've gotten around this by having a script restart the docker container every hour, but was wondering if you had any ideas about the below? 

Standard docker install from your repo with the suggested run arguments. Only difference is im running a CNI so using the broker command.. 

`2020-06-18 14:29:42,583 Transport security disabled!
2020-06-18 14:29:42,586 Connected to MQTT broker
2020-06-18 23:00:03,669 Fatal error: protocol.data_received() call failed.

protocol: <cbus.daemon.cmqttd.CBusHandler object at 0x154182706fd0>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
File "/usr/lib/python3.8/asyncio/selector_events.py", line 860, in _read_ready__data_received
self._protocol.data_received(data)
File "/usr/lib/python3.8/site-packages/cbus/protocol/buffered_protocol.py", line 79, in data_received
raise ValueError(
ValueError: Received data would make the buffer exceed the maximum limit, buffer dropped!`

**Comment by micolous** [comment]
It sounds like that part of the code got itself wedged.

Can you make a packet capture of the communications on the Raspberry Pi leading up to that point?  You should be able to do this with:

```
tcpdump -i eth0 -p -w capture.pcap 'host 192.0.2.1'
```

Where `192.0.2.1` is replaced with your CNI's IP address.

**Comment by redging-very-well** [comment]
@micolous  I see you had a branch to change these exceptions to warnings; any chance this could get merged?
https://github.com/micolous/cbus/compare/master...buffer-size
