### ISSUE TITLE
Will this work with the Wiser as my IP interface?

### ISSUE THREAD

**Issue by aaranstent** [micolous/cbus#27]
Hi, just trying to understand if the Wiser can be used as the bridge between the IP network and the C-BUS network like it is with tools make use of the C-GATE software.

**Comment by aaranstent** [comment]
I am getting errors and am thinking this may be related to the Wiser as opposed to a CNI interface?

```
Using TCP CNI at 192.168.1.10:10001
,Using TLS to connect to MQTT broker.
,/etc/cmqttd/certificates not found, using Python CA store.
,/etc/cmqttd/client.pem and/or /etc/cmqttd/client.key not found, not using client certificates for authentication.
,/etc/cmqttd/auth not found; skipping MQTT authentication.
,/etc/cmqttd/project.cbz not found; using generated labels.
,
,Local time zone: Australia/Melbourne
,Current time: Sun, 05 Sep 2021 17:12:44 +1000
,Running with flags: --broker-address 192.168.1.193 --timesync 300 --tcp 192.168.1.10:10001
,Traceback (most recent call last):
,  File "/usr/bin/cmqttd", line 33, in <module>
,    sys.exit(load_entry_point('cbus==0.2', 'console_scripts', 'cmqttd')())
,  File "/usr/lib/python3.8/site-packages/cbus/daemon/cmqttd.py", line 474, in main
,    run(_main())
,  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
,    return loop.run_until_complete(main)
,  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
,    return future.result()
,  File "/usr/lib/python3.8/site-packages/cbus/daemon/cmqttd.py", line 467, in _main
,    mqtt_client.connect(option.broker_address, port, option.broker_keepalive)
,  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 937, in connect
,    return self.reconnect()
,  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 1071, in reconnect
,    sock = self._create_socket_connection()
,  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
,    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
,  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
,    raise err
,  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
,    sock.connect(sa)
,ConnectionRefusedError: [Errno 111] Connection refused
,
```

**Comment by lowgoz** [comment]
heyhey

If you search the Cbus forums, there's actually a wiser script you can run to connect your wiser to MQTT direct which would be a better solutions !

**Comment by micolous** [comment]
**Short answer:** no, and it never will.

This software **totally replaces** Wiser -- you need to unplug your Wiser, and connect to the CNI's IP address directly.

Wiser interferes with the PCI inside of the CNI, which will screw up `cmqttd` and friends.  Wiser is also extremely insecure with very outdated software, I don't recommend anyone use it.

You also need to make sure there is a route from your Docker container to your CNI – which looks like one of the causes of the error you're seeing.
