### ISSUE TITLE
Incompatible python? 

### ISSUE THREAD

**Issue by bonicb** [micolous/cbus#28]
Hi and thanks for work put in to this project. 
I am attempting to run this on docker with portainer and am running in i into these errors in my log. It appears the dockerfile has pulled python 3.8 are there incompatibilitys between 3.7 and 3.8 causing this? I am a novice with docker. Thanks. 

--------------------

Using TCP CNI at 192.168.3.240:10001

Using TLS to connect to MQTT broker.

/etc/cmqttd/certificates not found, using Python CA store.

/etc/cmqttd/client.pem and/or /etc/cmqttd/client.key not found, not using client certificates for authentication.

/etc/cmqttd/auth not found; skipping MQTT authentication.

/etc/cmqttd/project.cbz not found; using generated labels.

Local time zone: Australia/Hobart

Current time: Thu, 07 Oct 2021 08:48:37 +1100

Running with flags: --broker-address 192.168.3.164 --timesync 300 --broker-port 1883 --tcp 192.168.3.240:10001

Traceback (most recent call last):

  File "/usr/bin/cmqttd", line 33, in <module>

    sys.exit(load_entry_point('cbus==0.2', 'console_scripts', 'cmqttd')())

  File "/usr/lib/python3.8/site-packages/cbus/daemon/cmqttd.py", line 474, in main

    run(_main())

  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run

    return loop.run_until_complete(main)

  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete

    return future.result()

  File "/usr/lib/python3.8/site-packages/cbus/daemon/cmqttd.py", line 467, in _main

    mqtt_client.connect(option.broker_address, port, option.broker_keepalive)

  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 937, in connect

    return self.reconnect()

  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 1100, in reconnect

    sock.do_handshake()

  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake

    self._sslobj.do_handshake()

ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by bonicb** [comment]
This was resolved by disabling tls. i am yet to enable it on my mosqitto server.
